name: absensi_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.8.5
  firebase_core: ^2.15.1
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  firebase_storage: ^11.2.6
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  firebase_auth: ^4.7.3
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: 's'
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        
    - family: Pacifico 
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
      
    - family: Source Sans Pro
      fonts: 
        - asset: fonts/SourceSansPro-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'images/sinarindo.png'